version: '3'
services: 
    nginx:
        image: nginx
        ports:
            - 80:80
    flask:
        build:
            context: ./
            dockerfile: Dockerfile
        image: python
        container_image: python
        volumes: 
            - ./:/
