version: '3'
services: 
    nginx:
        image: nginx:alpine
        container_name: nginx
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./proxy/certs:/etc/nginx/certs
        networks: 
            - my-network
        ports:
            - 80:80
            - 443:443
    flask:
        build:
            context: ./
            dockerfile: Dockerfile
            #image: dockerflask
        container_name: flask
        volumes: 
            - ./:/code/
        environment:
            - FLASK_APP=/code/run.py
              #command: flask run --host=0.0.0.0
              #        command: python run.py
        #ports:
       # ports:
        #    - 8080:5000
        
        networks: 
            my-network:
                aliases:
                    - flask-app

networks: 
    my-network:
